### ISSUE TITLE
Preview transparancy background overlaps

### ISSUE THREAD

**Issue by KxmischesDomi** [alabsi91/reanimated-color-picker#31]
### Description

When the preview style there is a set border radius that is bigger than zero it causes a unclean overlay of the transparancy grid below it to overlap which results in an ugly looking edge.

‏‎‌‎‌‍‎‍‎‎‏‎‏‎‌‏‍‌‏‍‎‍‍‎‏‏‌‌‏‌‎‎‍‌‌‍‌‎‌‏‎‌‍‏‏‌‏‍‍‎‎‎‍‏‎‍‌‏‌‏‎‏‎‎‏‎‍‏‎‍‌‌‎‌‌‍‍‍‍‏‏‎‎‏‍‌‎‏‏‍‌‌‌‌‍‏
![image](https://user-images.githubusercontent.com/67184131/230726776-e6caccb4-5e7a-466b-b211-823e2a4cf053.png)

### Steps to reproduce

1. Add a `<Preview />` Component
2. Add a style prop with a border radius > 0

### Reanimated Color Picker version

2.2.0

### React Native version

0.71.6

### React Native Reanimated version

2.14.4

### React Native Gesture Handler version

2.9.0

### Platforms

Android, Web

### JavaScript runtime

JSC

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

**Comment by KxmischesDomi** [comment]
This is not happening on ios

**Comment by KxmischesDomi** [comment]
Also there is another issue with transparancy that this stuff sometimes happens when adding a transparancy. It should also be possible to block the alpha setting completely from the color picker if you don't want it

![qemu-system-x86_64_uBQXwOdCiP](https://user-images.githubusercontent.com/67184131/230732861-d389c574-6363-4a33-ba5a-f188da821b64.png)

**Comment by alabsi91** [comment]
Unfortunately, I couldn't solve the unclean overlay issue since it depends on both the rendering engine and the screen DPI. However, I'm currently working on fixing the preview transparent issue. If you could provide the exact style you're applying, that would be really helpful. In the meantime, I suggest trying this workaround, which might help:

Instead of using the Preview component, consider using PreviewText and applying your style to its container.

```tsx
// inside your component
const selectedColor = useSharedValue("#fff");
const previewColorStyle = useAnimatedStyle(() => ({ backgroundColor: selectedColor.value }))

const onColorChange = ({ hex }) => {
  selectedColor.value = hex;
}

// inside the color picker wrapper
  <Animated.View style={[styles.previewContainer, previewColorStyle]}>
    <PreviewText colorFormat='hex' />
  </Animated.View>
```

**Comment by KxmischesDomi** [comment]
Wouldn't it be a solution to only display it when the transparancy falls below a certain threshold?

**Comment by KxmischesDomi** [comment]
Also my current styles:

Container: 
```css
                            width: "100%",
                            height: "50%",
                            borderRadius: 0,
                            borderTopRightRadius: 32,
                            borderTopLeftRadius: 32,
```

Text:
```css
                                fontSize: 20
```

**Comment by KxmischesDomi** [comment]
Also your workaround doesn't really seem to work for me. The text is working properly but the color isn't at all. Neither the default or the changed color is showing up properly. Also the text should include a contrast check like in the normal Preview.

**Comment by alabsi91** [comment]
The issue where two layers with the same border radius on top of each other do not match exactly is likely caused by the way the graphics are rendered by the operating system or the web browser. 

Rendering engines such as Core Animation on iOS, Skia on Android, and WebKit on the web use anti-aliasing to smooth out the edges of graphics to make them appear less jagged. This process can cause a slight overlap or gap between objects that have the same border radius, especially if they have different colors or transparency values.

While anti-aliasing can improve the overall appearance of graphics, it can also lead to small inconsistencies between objects that are close together. This is a common issue in design and is often addressed through careful adjustment of the graphic elements or the use of different techniques or tools to achieve the desired effect.
